import streamlit as st
import random
import base64

# Inicializa variáveis da sessão
if "page" not in st.session_state:
    st.session_state.page = "home"
if "sentimento" not in st.session_state:
    st.session_state.sentimento = None
if "feedback" not in st.session_state:
    st.session_state.feedback = None

# Configuração da página
st.set_page_config(page_title="Feedback de Sentimento", page_icon="🙂", layout="wide")

# Estilos responsivos
st.markdown("""
    <style>
    /* Botões responsivos */
    div.stButton > button {
        background-color: #e0f0ff !important;
        color: #2563eb !important;
        font-size: 18px !important;  /* fixo no desktop */
        font-weight: bold !important;
        height: auto !important;
        padding: 0.8em !important;
        border-radius: 12px !important;
        margin: 0.5em !important;
        display: flex;
        align-items: center;
        justify-content: center;
        width: 100%;
        min-width: 120px;
    }

    /* Título principal */
    .main-title {
        text-align: center;
        font-size: 28px; /* fixo no desktop */
        color: #FF8C00;
        font-weight: bold;
        margin-bottom: 1em;
    }

    .title-container {
        display: flex;
        justify-content: center;
        align-items: center;
        flex-wrap: wrap;
        gap: 0.5em;
        font-size: 22px; /* fixo no desktop */
        text-align: center;
    }

    .title-heart {
        animation: heartbeat 1s infinite;
        color: #FFD700;
    }

    @keyframes heartbeat {
        0%, 100% { transform: scale(1); }
        25%, 75% { transform: scale(1.2); }
        50% { transform: scale(1); }
    }

    /* Footer */
    .footer-container {
        text-align: center;
        margin-top: 3em;
    }

    .footer-text {
        font-size: 18px;
        font-weight: bold;
        color: #FF8C00;
        margin-bottom: 1em;
    }

    .footer-logo img {
        max-width: 150px;
        width: 100%;
        height: auto;
        display: block;
        margin: 0 auto;
    }

    /* Mobile: aumenta proporcionalmente */
    @media(max-width: 768px) {
        div.stButton > button { font-size: 5vw !important; }
        .main-title { font-size: 6vw; }
        .title-container { font-size: 4.5vw; }
        .footer-text { font-size: 4vw; }
    }
    </style>
""", unsafe_allow_html=True)

# Feedbacks
feedbacks = {
    "feliz": [
    "Sorria, a felicidade é contagiante.",
    "Hoje é um bom dia para ser feliz.",
    "A alegria nasce de pequenos momentos.",
    "Valorize o que te faz sorrir.",
    "A felicidade está nas coisas simples.",
    "Cada riso é uma vitória sobre a tristeza.",
    "Aproveite cada instante com gratidão.",
    "Faça da alegria o seu estilo de vida.",
    "O mundo é mais bonito quando você sorri.",
    "A felicidade é um presente que você se dá.",
    "Celebre as pequenas conquistas.",
    "Um coração feliz transforma o ambiente.",
    "A alegria é energia que se multiplica.",
    "Sorrir é a melhor maneira de começar o dia.",
    "A felicidade é uma escolha diária.",
    "A vida fica leve com um sorriso no rosto.",
    "A gratidão torna a felicidade mais intensa.",
    "Faça do seu dia uma celebração.",
    "Rir de si mesmo é um sinal de sabedoria.",
    "Sorrir é compartilhar luz com o mundo.",
    "Felicidade é perceber a beleza ao redor.",
    "Abrace o que te faz bem.",
    "A alegria se espalha em boas ações.",
    "Valorize cada instante de felicidade.",
    "O riso cura e fortalece.",
    "Seja feliz com quem você é.",
    "Pequenas alegrias constroem grandes dias.",
    "Felicidade é a soma de momentos simples.",
    "Um coração alegre atrai coisas boas.",
    "A alegria é uma forma de coragem.",
    "Viva com leveza e gratidão.",
    "Encontre felicidade nas pequenas vitórias.",
    "A felicidade verdadeira vem de dentro.",
    "Aprecie cada momento presente.",
    "Felicidade é compartilhar amor.",
    "Sorrir abre portas para oportunidades.",
    "Viva com alegria genuína.",
    "Alegria é um estado de espírito.",
    "Espalhe felicidade por onde passar.",
    "O riso é uma forma de resistência.",
    "Felicidade é estar em paz consigo mesmo.",
    "Um dia feliz começa com pensamentos positivos.",
    "A alegria se multiplica quando compartilhada.",
    "Celebre suas conquistas diariamente.",
    "Sorrir transforma dias comuns em especiais.",
    "Felicidade é viver o presente intensamente.",
    "Valorize os momentos de riso.",
    "Ser feliz é um ato de coragem.",
    "O mundo precisa do seu sorriso.",
    "Alegria é escolher olhar o lado bom.",
    "Felicidade é fazer o que se ama.",
    "Viva cada dia com entusiasmo.",
    "O riso é a música da alma.",
    "Encontre prazer nas pequenas coisas.",
    "Felicidade é sentir gratidão constantemente.",
    "Um coração alegre ilumina vidas.",
    "Valorize quem te faz feliz.",
    "Felicidade é encontrar leveza na vida.",
    "Viva momentos que te façam sorrir.",
    "A alegria é contagiante.",
    "Celebre a vida em cada gesto.",
    "Felicidade é estar presente consigo mesmo.",
    "O riso cura e renova.",
    "Alegria é perceber a beleza do cotidiano.",
    "Sorria para atrair coisas boas.",
    "Felicidade é se sentir pleno.",
    "Aprecie o hoje com alegria.",
    "O sorriso é a linguagem universal da felicidade.",
    "Felicidade é viver com leveza e amor.",
    "A alegria é fruto de pensamentos positivos.",
    "Viva com gratidão e felicidade.",
    "Pequenos momentos de felicidade são eternos.",
    "O riso transforma energia negativa em positiva.",
    "Felicidade é perceber que você é suficiente.",
    "Celebre cada instante de alegria.",
    "Sorria, a vida fica mais leve.",
    "A felicidade se encontra nas coisas simples.",
    "Alegria é compartilhar bons momentos.",
    "Felicidade é um hábito diário.",
    "O riso é a melhor terapia.",
    "Sinta alegria por quem você é.",
    "Valorize os pequenos momentos de riso.",
    "Felicidade é escolher olhar o lado bom.",
    "A alegria nasce quando você aprecia o presente.",
    "Sorrir transforma sua energia.",
    "Felicidade é ser grato pelo agora.",
    "A alegria ilumina quem está ao redor.",
    "Celebre a vida com pequenos gestos.",
    "Um coração feliz atrai coisas boas.",
    "Felicidade é viver sem arrependimentos.",
    "Sorria para você e para o mundo.",
    "Alegria é aceitar e amar a si mesmo.",
    "Felicidade é encontrar sentido em pequenas coisas.",
    "O riso é a melhor expressão da alma.",
    "Valorize cada instante de alegria.",
    "A felicidade é contagiosa quando compartilhada.",
    "Felicidade é a soma de momentos leves.",
    "Celebre cada dia com gratidão.",
    "Sorrir é um ato de amor-próprio.",
    "Felicidade é sentir paz e contentamento."
],
    "triste": [
    "Você é mais forte do que imagina.",
    "A tristeza é passageira, assim como as nuvens no céu.",
    "Um passo de cada vez já é progresso.",
    "Respire fundo, dias melhores virão.",
    "O sol sempre volta a brilhar depois da tempestade.",
    "Sua vida tem muito valor.",
    "Tudo bem não estar bem hoje.",
    "Você não está sozinho nessa caminhada.",
    "Cada dificuldade é uma oportunidade de crescimento.",
    "O amanhã guarda novas possibilidades.",
    "Já superou tantas coisas, vai superar essa também.",
    "Permita-se descansar, mas não desistir.",
    "Chorar também é uma forma de cura.",
    "Você merece acolhimento e paz.",
    "A dor não define quem você é.",
    "Cada cicatriz conta uma história de força.",
    "Há beleza até nos dias cinzentos.",
    "Pequenas vitórias também são importantes.",
    "O amor próprio é o maior abrigo.",
    "Sua coragem já te trouxe até aqui.",
    "Nada dura para sempre, nem a tristeza.",
    "Você merece se sentir leve de novo.",
    "Há sempre alguém disposto a te ouvir.",
    "Um sorriso seu pode transformar o mundo.",
    "Sua existência é importante.",
    "Se permita recomeçar quantas vezes precisar.",
    "Até as flores precisam de chuva para crescer.",
    "Cada dia traz uma nova chance.",
    "Você é especial do jeitinho que é.",
    "O tempo cura feridas que parecem eternas.",
    "Sua vida faz diferença para muita gente.",
    "Olhe com carinho para si mesmo hoje.",
    "A tristeza não diminui sua luz interior.",
    "O melhor ainda está por vir.",
    "O simples fato de você existir já é lindo.",
    "Você merece amor, paz e alegria.",
    "Não se cobre tanto, tudo tem seu tempo.",
    "Acredite: você vai sorrir de novo.",
    "Sua história ainda está sendo escrita.",
    "A vida é feita de altos e baixos, e isso é normal.",
    "Você tem direito a sentir, sem culpa.",
    "O silêncio também é um abraço da alma.",
    "Confie no seu processo de cura.",
    "Até no inverno, a primavera se prepara para chegar.",
    "Seu coração é capaz de se refazer.",
    "Você é uma inspiração, mesmo nos dias difíceis.",
    "A luz volta a brilhar quando menos se espera.",
    "Nunca subestime sua capacidade de recomeçar.",
    "Ser vulnerável também é ser forte.",
    "Você não precisa carregar tudo sozinho.",
    "Há esperança em cada novo amanhecer.",
    "Você é digno de amor e respeito.",
    "O futuro reserva bons encontros e sorrisos.",
    "Cada dor traz consigo uma lição.",
    "Tudo passa, até os momentos mais pesados.",
    "Você tem coragem para atravessar qualquer tempestade.",
    "Sua alma merece descanso e acolhimento.",
    "O recomeço pode ser lindo.",
    "Há beleza escondida até no caos.",
    "Sua vida tem propósito.",
    "Você já venceu dias difíceis antes.",
    "O choro rega a semente da superação.",
    "Há sempre uma saída, mesmo que pareça invisível.",
    "Você é mais valioso do que qualquer tristeza.",
    "Cada amanhecer é uma nova página.",
    "Seu coração merece ternura.",
    "Você pode transformar dor em força.",
    "Há sempre motivos para continuar, mesmo que pequenos.",
    "A tristeza não define sua essência.",
    "O tempo traz novos ventos e novas cores.",
    "Você merece se sentir amado.",
    "Não desista de acreditar em dias bons.",
    "O mundo precisa do que só você pode oferecer.",
    "Sua caminhada importa.",
    "Você tem mais força do que reconhece.",
    "Cada dificuldade vencida aumenta sua resiliência.",
    "Você não precisa ter todas as respostas agora.",
    "Um coração machucado também pode florescer.",
    "Pequenos gestos podem renovar sua esperança.",
    "Você é capaz de encontrar paz dentro de si.",
    "Nunca esqueça o quanto já evoluiu.",
    "A tristeza é um visitante, não um morador.",
    "Você merece leveza e alegria.",
    "O universo sempre traz novas oportunidades.",
    "Você é amado exatamente como é.",
    "Nenhuma noite é eterna.",
    "Há força no seu silêncio e nas suas pausas.",
    "Você é digno de dias felizes.",
    "Até a dor pode se transformar em aprendizado.",
    "Você não está preso ao seu passado.",
    "Cada passo em frente já é uma vitória.",
    "A esperança é uma chama que nunca apaga.",
    "Você pode recomeçar sempre que precisar.",
    "Seu sorriso vai voltar, confie.",
    "O amor é mais forte que qualquer tristeza.",
    "Você tem tudo o que precisa dentro de si.",
    "A dor é temporária, sua essência é eterna.",
    "Nunca duvide do seu valor.",
    "Você é luz, mesmo em dias nublados.",
    "O melhor capítulo da sua história ainda está por vir."
],
    "ansioso": [
    "Respire fundo, você está seguro agora.",
    "Um pensamento de cada vez, um passo de cada vez.",
    "Acalme sua mente, seu coração sabe o caminho.",
    "Você não precisa controlar tudo.",
    "Sua respiração é sua âncora.",
    "Ansiedade não é fraqueza, é apenas um sinal de alerta.",
    "Tudo bem desacelerar.",
    "Você está fazendo o seu melhor, e isso é suficiente.",
    "Inspire paz, expire preocupação.",
    "A calma sempre encontra espaço dentro de você.",
    "Você não é sua ansiedade.",
    "O que você sente vai passar.",
    "Foque no presente, o agora é suficiente.",
    "Você já venceu momentos difíceis antes.",
    "Sua mente merece descanso.",
    "O amanhã pode esperar, viva o hoje.",
    "Sua paz é prioridade.",
    "A vida não exige perfeição, apenas presença.",
    "Você pode encontrar tranquilidade mesmo em dias agitados.",
    "Seu corpo sabe como se equilibrar, confie nele.",
    "Nenhuma onda é maior que o oceano da sua força.",
    "Você pode pausar sem culpa.",
    "A ansiedade não define quem você é.",
    "Um momento de silêncio pode curar muito.",
    "Sua calma é mais poderosa que o medo.",
    "Você é capaz de lidar com isso.",
    "Confie no tempo, ele traz equilíbrio.",
    "Não há problema em se sentir ansioso, é humano.",
    "Você pode se acolher agora mesmo.",
    "Seu coração merece leveza.",
    "Respire devagar, tudo vai se ajustar.",
    "Você não precisa ter todas as respostas.",
    "A calma cresce quando você se permite parar.",
    "A ansiedade é como o vento: forte, mas passageiro.",
    "Um dia de cada vez é o suficiente.",
    "Você pode ser gentil consigo mesmo agora.",
    "O futuro não precisa ser resolvido hoje.",
    "Você merece tranquilidade.",
    "O presente é o lugar mais seguro para estar.",
    "Você já superou muitos medos antes.",
    "Seu valor não depende do que você faz, mas de quem você é.",
    "O controle não traz paz, mas a confiança sim.",
    "Sua respiração te reconecta à calma.",
    "Você pode encontrar equilíbrio mesmo em meio ao caos.",
    "Você é mais resiliente do que pensa.",
    "A ansiedade é um sinal, não um destino.",
    "Você pode soltar o que não pode controlar.",
    "Permita-se desacelerar sem se culpar.",
    "Você é mais do que seus pensamentos acelerados.",
    "Sua paz está dentro de você, sempre.",
    "O agora é tudo o que você precisa viver.",
    "Você pode se acolher como acolheria alguém que ama.",
    "A calma chega quando você respira devagar.",
    "Não há urgência em ser perfeito.",
    "Seu coração merece serenidade.",
    "Ansiedade não é um inimigo, é apenas um mensageiro.",
    "Você pode ouvir seus sentimentos sem se perder neles.",
    "Uma pausa é um ato de autocuidado.",
    "Você não está sozinho nessa luta.",
    "Você é digno de paz.",
    "Cada respiração é uma nova chance de recomeço.",
    "Seus pensamentos não são verdades absolutas.",
    "Você já passou por isso antes e sobreviveu.",
    "O mundo pode esperar um pouco.",
    "Sua mente pode aprender a descansar.",
    "Você é mais do que o medo que sente.",
    "O futuro não precisa ser previsto, apenas vivido.",
    "A calma pode florescer em meio ao medo.",
    "Você tem o direito de desacelerar.",
    "A ansiedade não dura para sempre.",
    "Você é corajoso por enfrentar seus medos.",
    "Um momento de respiração consciente já é vitória.",
    "Você não precisa correr, pode caminhar no seu tempo.",
    "Sua paz interior é sua fortaleza.",
    "Você merece descanso emocional.",
    "O amanhã se resolve amanhã.",
    "Cada pequena vitória é importante.",
    "Você pode soltar o peso que não lhe pertence.",
    "Sua mente merece carinho.",
    "A calma está no simples.",
    "Você pode transformar tensão em aprendizado.",
    "Seus sentimentos não te definem.",
    "Você tem mais controle do que imagina.",
    "A ansiedade é temporária, mas sua força é permanente.",
    "Você pode escolher se tratar com gentileza agora.",
    "O silêncio interior é possível.",
    "Você merece se sentir leve.",
    "Nenhuma tempestade é eterna.",
    "Seu corpo e mente querem equilíbrio, permita.",
    "Você é capaz de criar momentos de calma.",
    "O agora é sempre suficiente.",
    "Você não precisa estar em alerta o tempo todo.",
    "Sua vida não precisa de pressa.",
    "O medo não é maior que sua coragem.",
    "Você já é suficiente, exatamente como é.",
    "O descanso é tão importante quanto a ação.",
    "Você pode respirar fundo e recomeçar quantas vezes quiser.",
    "Sua ansiedade não é um fracasso, é apenas um sinal de cuidado.",
    "Há serenidade no simples ato de pausar.",
    "Você é forte, capaz e digno de tranquilidade."
],
    "motivado": [
    "Levante-se e faça acontecer.",
    "Cada passo conta para a vitória.",
    "O esforço de hoje será a conquista de amanhã.",
    "A ação transforma sonhos em realidade.",
    "Persistência é a chave do sucesso.",
    "Você é capaz de mais do que imagina.",
    "Nada acontece sem atitude.",
    "Comece agora, o momento é seu.",
    "O sucesso recompensa os determinados.",
    "Cada desafio é uma oportunidade de crescimento.",
    "Não espere, construa seu caminho.",
    "A disciplina supera o talento sem esforço.",
    "Grandes resultados começam com pequenos passos.",
    "Faça de cada dia um avanço.",
    "O impossível existe apenas na mente.",
    "A motivação vem de dentro.",
    "Transforme obstáculos em combustível.",
    "A ação de hoje define o amanhã.",
    "Persista, os resultados virão.",
    "Foque no progresso, não na perfeição.",
    "Você é a força que move sua vida.",
    "O sucesso começa com iniciativa.",
    "Transforme ideias em realizações.",
    "Acredite, insista, conquiste.",
    "Faça cada esforço valer a pena.",
    "Grandes sonhos exigem grandes ações.",
    "Avance mesmo quando for difícil.",
    "Não pare até se orgulhar.",
    "A ação constante gera resultados duradouros.",
    "O agora é o momento de agir.",
    "Tenha coragem para ir além.",
    "Cada esforço te aproxima da meta.",
    "Sua determinação é sua maior arma.",
    "Persistir é vencer lentamente.",
    "Transforme intenção em ação.",
    "A disciplina cria liberdade.",
    "O sucesso é feito de passos consistentes.",
    "Avance mesmo com medo.",
    "A motivação se fortalece com resultados.",
    "Pequenos passos diários geram grandes conquistas.",
    "Faça do seu esforço uma rotina.",
    "O futuro é construído hoje.",
    "Cada ação conta.",
    "Foque no que você pode controlar.",
    "A persistência transforma sonhos em realidade.",
    "Acredite na sua capacidade.",
    "O esforço contínuo gera excelência.",
    "Concentre-se no progresso, não na dificuldade.",
    "Avance com propósito.",
    "A ação é o antídoto da procrastinação.",
    "Faça acontecer, não espere acontecer.",
    "Sua dedicação faz a diferença.",
    "Grandes conquistas exigem coragem.",
    "Mova-se, mesmo devagar, mas com constância.",
    "Cada dia é uma oportunidade de progresso.",
    "Transforme desafios em vitórias.",
    "A determinação abre portas.",
    "Construa sua própria história de sucesso.",
    "O trabalho duro supera qualquer dificuldade.",
    "Continue, mesmo quando ninguém observa.",
    "O progresso começa com o primeiro passo.",
    "Sua ação inspira resultados.",
    "Cada esforço vale a pena.",
    "Faça de cada obstáculo uma lição.",
    "Avance com confiança.",
    "Persistência é mais poderosa que sorte.",
    "O sucesso é fruto de ação consistente.",
    "Tenha coragem para seguir adiante.",
    "Trabalhe silenciosamente, conquiste ruidosamente.",
    "Não espere motivação, crie disciplina.",
    "A ação transforma intenção em realidade.",
    "Foque no que te leva adiante.",
    "A cada passo, você se fortalece.",
    "Faça de hoje um dia produtivo.",
    "Grandes metas exigem grandes esforços.",
    "Persistir é o caminho para vencer.",
    "Transforme vontade em ação.",
    "A determinação constrói resultados.",
    "Cada esforço aumenta sua confiança.",
    "Não desista, a vitória está próxima.",
    "Concentre-se no que te impulsiona.",
    "A persistência é sua aliada.",
    "O futuro pertence aos que agem.",
    "Trabalhe duro em silêncio e celebre em público.",
    "A ação constante gera progresso contínuo.",
    "Cada passo dado é um passo mais perto do objetivo.",
    "Faça de cada dia uma conquista.",
    "O sucesso exige atitude, não sorte.",
    "Avance com coragem e foco.",
    "A motivação cresce com resultados.",
    "Cada desafio é uma oportunidade de superação.",
    "Não pare até alcançar sua meta.",
    "A disciplina cria sucesso.",
    "A persistência transforma esforço em vitória.",
    "Faça do seu hoje o alicerce do amanhã.",
    "Conquistar exige dedicação diária.",
    "Cada ação te aproxima do sonho.",
    "Tenha coragem para ir além do esperado.",
    "Transforme obstáculos em trampolins.",
    "Ação + persistência = sucesso."
],
    "calmo": [
    "Que bom que você está calmo, isso é ótimo para tomar decisões claras.",
    "Sua calma é inspiradora para quem está ao seu redor.",
    "Manter a calma ajuda a enfrentar qualquer desafio.",
    "É admirável ver você tão centrado.",
    "Sua serenidade transmite segurança aos outros.",
    "Estar calmo mostra grande controle emocional.",
    "Que tranquilidade contagiante!",
    "A calma permite que você pense melhor antes de agir.",
    "Sua postura calma é um exemplo de maturidade.",
    "É ótimo ver você lidando com a situação com serenidade.",
    "Sua calma ajuda a resolver problemas com mais facilidade.",
    "Que bom que você está em paz consigo mesmo.",
    "Sua serenidade faz diferença no ambiente ao redor.",
    "É inspirador ver alguém tão tranquilo.",
    "Manter a calma é uma habilidade valiosa.",
    "Sua calma transmite confiança aos outros.",
    "A forma como você permanece calmo é admirável.",
    "Que bom ver que você está centrado e equilibrado.",
    "Sua tranquilidade ajuda a reduzir o estresse ao redor.",
    "É ótimo ver você respirando fundo e mantendo a calma.",
    "Sua serenidade ajuda a clarear a mente.",
    "Manter a calma é sinal de inteligência emocional.",
    "Sua postura calma faz com que todos se sintam mais seguros.",
    "Que bom que você consegue manter o controle emocional.",
    "Sua calma é um exemplo para todos nós.",
    "Estar calmo ajuda a enfrentar desafios com mais clareza.",
    "Sua tranquilidade é contagiante.",
    "É ótimo ver você tão equilibrado emocionalmente.",
    "A calma que você demonstra é inspiradora.",
    "Manter a serenidade em momentos difíceis é uma grande virtude.",
    "Sua calma ajuda a pensar melhor antes de agir.",
    "Que bom que você está lidando com tudo de forma serena.",
    "Sua postura tranquila é admirável.",
    "A forma como você mantém a calma é um exemplo de autocontrole.",
    "É ótimo ver você respirando fundo e permanecendo calmo.",
    "Sua serenidade ajuda a resolver problemas com clareza.",
    "Manter a calma é uma habilidade que poucos dominam.",
    "Sua tranquilidade inspira confiança.",
    "Que bom ver você tão centrado.",
    "Sua calma é uma força silenciosa.",
    "É inspirador ver alguém tão sereno diante das situações.",
    "Manter a calma ajuda a lidar melhor com imprevistos.",
    "Sua serenidade transmite paz aos outros.",
    "Que bom que você está conseguindo manter o equilíbrio.",
    "Sua postura calma é um exemplo de maturidade emocional.",
    "Estar calmo é uma grande vantagem em qualquer situação.",
    "Sua tranquilidade ajuda a criar um ambiente mais harmonioso.",
    "É ótimo ver você mantendo a calma em meio ao caos.",
    "Sua serenidade é admirável e inspiradora.",
    "Manter a calma permite tomar decisões mais sábias.",
    "Sua calma transmite segurança para todos ao redor.",
    "Que bom que você consegue manter o controle das emoções.",
    "Sua tranquilidade é um exemplo de paciência.",
    "É inspirador ver alguém lidar com tudo de forma tão calma.",
    "Manter a calma ajuda a ver soluções que outros não veem.",
    "Sua serenidade é contagiante e tranquiliza todos ao redor.",
    "Que bom ver você equilibrado e centrado.",
    "Sua calma ajuda a reduzir o estresse das pessoas próximas.",
    "É admirável ver você lidando com a situação de forma serena.",
    "Sua postura calma reflete grande autocontrole.",
    "Manter a calma é um sinal de sabedoria emocional.",
    "Sua tranquilidade faz diferença no ambiente.",
    "É ótimo ver você respirando fundo e mantendo a serenidade.",
    "Sua calma permite enfrentar qualquer situação com clareza.",
    "Que bom que você está conseguindo permanecer centrado.",
    "Sua serenidade transmite confiança e segurança.",
    "Manter a calma ajuda a tomar decisões mais acertadas.",
    "Sua tranquilidade é admirável e inspiradora.",
    "É inspirador ver você tão equilibrado emocionalmente.",
    "Sua calma é uma força silenciosa que todos percebem.",
    "Que bom ver você lidando com tudo de forma tranquila.",
    "Sua serenidade ajuda a criar um ambiente harmonioso.",
    "Manter a calma é essencial para resolver problemas complexos.",
    "Sua postura calma transmite maturidade.",
    "É ótimo ver você mantendo o equilíbrio emocional.",
    "Sua calma inspira todos ao seu redor.",
    "Que bom que você consegue se manter sereno em qualquer situação.",
    "Sua tranquilidade é um grande exemplo de paciência.",
    "Manter a calma ajuda a enxergar soluções melhores.",
    "Sua serenidade faz diferença em momentos de tensão.",
    "É admirável ver você tão centrado diante dos desafios.",
    "Sua calma é uma qualidade valiosa.",
    "Que bom ver você lidando com situações difíceis com serenidade.",
    "Sua postura tranquila transmite confiança aos outros.",
    "Manter a calma é um sinal de grande inteligência emocional.",
    "Sua tranquilidade ajuda a reduzir a tensão ao redor.",
    "É inspirador ver você lidar com tudo de forma tão calma.",
    "Sua serenidade permite agir com clareza e confiança.",
    "Que bom que você consegue permanecer equilibrado.",
    "Sua calma ajuda a transformar desafios em oportunidades.",
    "Manter a serenidade é um exemplo para todos.",
    "Sua tranquilidade inspira confiança e respeito.",
    "É ótimo ver você lidando com tudo com tanta calma.",
    "Sua postura calma é admirável e inspiradora.",
    "Que bom que você mantém o equilíbrio mesmo em situações difíceis.",
    "Sua serenidade ajuda a tomar decisões melhores.",
    "Manter a calma é uma habilidade que faz diferença na vida.",
    "Sua tranquilidade transmite paz e segurança.",
    "É inspirador ver você tão calmo diante dos desafios.",
    "Sua calma ajuda a criar um ambiente mais positivo.",
    "Que bom ver você lidando com tudo de forma serena e centrada.",
    "Sua postura calma é um verdadeiro exemplo de autocontrole."
],
    "grato": [
    "A gratidão transforma qualquer dia.",
    "Valorize o que você tem hoje.",
    "Ser grato é reconhecer o valor da vida.",
    "Cada momento merece gratidão.",
    "A gratidão multiplica felicidade.",
    "Aprecie os pequenos gestos.",
    "Gratidão é a chave da paz interior.",
    "Agradeça antes de esperar.",
    "Reconhecer o bem transforma sua energia.",
    "A gratidão é um imã de coisas boas.",
    "Agradecer é se conectar com o presente.",
    "Ser grato aumenta sua resiliência.",
    "A vida é mais leve quando se é grato.",
    "A gratidão muda a percepção do mundo.",
    "Valorize cada aprendizado.",
    "Agradecer transforma desafios em lições.",
    "Gratidão é reconhecer que tudo tem propósito.",
    "Aprecie cada sorriso recebido.",
    "Ser grato fortalece relacionamentos.",
    "Agradecer é cultivar alegria.",
    "Reconheça as conquistas diárias.",
    "Gratidão é perceber o lado positivo da vida.",
    "Valorize quem está ao seu redor.",
    "Agradeça pelas pequenas vitórias.",
    "Ser grato transforma a rotina.",
    "Aprecie os momentos simples.",
    "Gratidão é um exercício diário.",
    "Agradecer é iluminar seu caminho.",
    "Valorize o presente, ele é único.",
    "Ser grato abre portas para novas oportunidades.",
    "Agradeça pelas lições aprendidas.",
    "Gratidão é amor em ação.",
    "Cada dia é um presente para agradecer.",
    "Reconheça as bênçãos ocultas.",
    "Gratidão é a essência da felicidade.",
    "Valorize o que você conquistou.",
    "Ser grato transforma desafios em crescimento.",
    "Agradecer é celebrar a vida.",
    "Gratidão aproxima você do que é essencial.",
    "Reconheça as pequenas alegrias.",
    "Agradeça por cada novo amanhecer.",
    "Gratidão é um caminho para a paz interior.",
    "Valorize cada pessoa que cruza seu caminho.",
    "Ser grato te torna mais leve.",
    "Aprecie as oportunidades do dia.",
    "Agradecer é reconhecer a abundância.",
    "Gratidão transforma perspectiva.",
    "Valorize cada gesto de carinho.",
    "Ser grato aumenta sua energia positiva.",
    "Agradeça pelas conquistas, grandes ou pequenas.",
    "Gratidão é reconhecer o presente da vida.",
    "Valorize as lições de cada experiência.",
    "Agradecer é atrair mais motivos para sorrir.",
    "Ser grato ilumina sua mente.",
    "Reconheça as bênçãos que muitas vezes passam despercebidas.",
    "Gratidão é aceitar o presente como ele é.",
    "Valorize cada passo da sua jornada.",
    "Agradecer fortalece seu espírito.",
    "Ser grato abre espaço para a abundância.",
    "Reconheça o amor que recebe diariamente.",
    "Gratidão transforma o ordinário em extraordinário.",
    "Aprecie cada momento de silêncio e paz.",
    "Valorize as pessoas que te apoiam.",
    "Ser grato muda sua forma de enxergar a vida.",
    "Agradecer é um ato de humildade.",
    "Gratidão transforma o que temos em suficiente.",
    "Reconheça o valor de cada experiência.",
    "Valorize a beleza do cotidiano.",
    "Ser grato é abraçar a vida com amor.",
    "Agradeça antes de dormir, sempre.",
    "Gratidão aumenta sua capacidade de amar.",
    "Valorize sua saúde e bem-estar.",
    "Ser grato te conecta com o que importa.",
    "Reconheça os bons momentos do passado.",
    "Agradecer transforma coração em lar.",
    "Gratidão é olhar para a vida com ternura.",
    "Valorize as pequenas conquistas diárias.",
    "Ser grato ilumina seu caminho.",
    "Reconheça cada oportunidade de aprendizado.",
    "Agradecer é viver com consciência.",
    "Gratidão é a força silenciosa da felicidade.",
    "Valorize cada gesto de bondade.",
    "Ser grato transforma qualquer dia em especial.",
    "Aprecie a beleza da natureza ao seu redor.",
    "Gratidão fortalece vínculos afetivos.",
    "Reconheça sua evolução diária.",
    "Ser grato torna a vida mais leve e alegre.",
    "Agradeça pelas dificuldades, elas ensinam.",
    "Gratidão é uma fonte de energia positiva.",
    "Valorize cada instante que respira.",
    "Ser grato transforma momentos comuns em inesquecíveis.",
    "Agradecer é reconhecer seu valor.",
    "Gratidão é um convite para a felicidade.",
    "Valorize cada oportunidade de crescer.",
    "Ser grato atrai mais motivos para sorrir.",
    "Reconheça cada gesto de generosidade.",
    "Agradecer abre o coração para novas experiências.",
    "Gratidão é uma escolha que muda tudo.",
    "Valorize cada momento de alegria.",
    "Ser grato é celebrar a vida em cada detalhe.",
    "Agradecer transforma dias comuns em especiais.",
    "Valorize cada gesto de bondade.",
    "Ser grato é reconhecer o valor da vida.",
    "Cada momento merece gratidão.",
    "Agradeça pelas pequenas vitórias.",
    "A gratidão abre portas para mais bênçãos.",
    "Valorize cada pessoa que cruza seu caminho.",
    "Ser grato fortalece o coração.",
    "Agradeça pelo presente de hoje.",
    "Reconhecer o bem multiplica a felicidade.",
    "Gratidão é perceber a abundância ao redor.",
    "Cada dia é um motivo para agradecer.",
    "Valorize cada lição aprendida.",
    "Ser grato transforma dificuldades em aprendizado.",
    "Agradeça pelo amor que recebe.",
    "Pequenos gestos merecem grande gratidão.",
    "A vida fica mais leve quando se é grato.",
    "A gratidão renova a alma.",
    "Agradeça mesmo pelas dificuldades.",
    "Valorize as oportunidades recebidas.",
    "Ser grato ilumina o caminho.",
    "Agradeça pelas pessoas que te apoiam.",
    "Reconhecer conquistas fortalece o espírito.",
    "Gratidão é a chave da paz interior.",
    "Cada respiração é um motivo para agradecer.",
    "Valorize o presente como ele é.",
    "Ser grato transforma rotina em alegria.",
    "Agradeça pelo aprendizado diário.",
    "A gratidão é força silenciosa da alma.",
    "Pequenas vitórias merecem grandes agradecimentos.",
    "Valorize cada gesto de carinho.",
    "Ser grato aproxima você da felicidade.",
    "Agradeça por cada amanhecer.",
    "A gratidão abre espaço para o novo.",
    "Cada desafio vencido é motivo para agradecer.",
    "Valorize a beleza das pequenas coisas.",
    "Ser grato é abraçar a vida com amor.",
    "Agradeça pelas experiências que ensinam.",
    "Gratidão transforma o ordinário em extraordinário.",
    "Valorize os momentos de alegria.",
    "Ser grato aumenta a paz interior.",
    "Agradeça pela sua força e coragem.",
    "Cada dia é uma oportunidade de gratidão.",
    "Reconhecer o bem traz mais bem.",
    "A gratidão é fonte de felicidade.",
    "Valorize cada passo da sua jornada.",
    "Ser grato inspira outros ao redor.",
    "Agradeça pelo simples fato de existir.",
    "A gratidão cria conexão com o presente.",
    "Cada gesto de bondade merece reconhecimento.",
    "Valorize a generosidade que recebe.",
    "Ser grato ilumina a vida.",
    "Agradeça pelas lições que a vida oferece.",
    "Gratidão transforma energia negativa em positiva.",
    "Valorize os momentos de silêncio e paz.",
    "Ser grato fortalece relações.",
    "Agradeça pelas pequenas conquistas.",
    "A gratidão é um hábito diário.",
    "Cada experiência é motivo para agradecer.",
    "Valorize a presença de quem te ama.",
    "Ser grato cria felicidade duradoura.",
    "Agradeça por cada oportunidade de crescimento.",
    "Gratidão transforma dificuldade em aprendizado.",
    "Valorize a vida e seus pequenos milagres.",
    "Ser grato mantém o coração leve.",
    "Agradeça por cada momento de alegria.",
    "A gratidão fortalece a mente.",
    "Valorize cada gesto de apoio recebido.",
    "Ser grato aumenta sua energia positiva.",
    "Agradeça pelo que você conquistou.",
    "Gratidão é reconhecer a beleza da vida.",
    "Valorize cada nova oportunidade.",
    "Ser grato inspira paz e amor.",
    "Agradeça pelo presente da vida.",
    "Cada dia é uma chance de ser grato.",
    "Gratidão transforma desafios em força.",
    "Valorize o aprendizado em cada erro.",
    "Ser grato cria plenitude interior.",
    "Agradeça pelos momentos de felicidade.",
    "A gratidão aproxima você do essencial.",
    "Valorize a jornada, não apenas o destino.",
    "Ser grato mantém a esperança viva.",
    "Agradeça pela energia positiva ao redor.",
    "Gratidão é aceitar a vida como ela é.",
    "Valorize a simplicidade do cotidiano.",
    "Ser grato transforma o presente em tesouro.",
    "Agradeça pelas experiências únicas.",
    "Cada gesto de amor merece gratidão.",
    "Gratidão é reconhecer o valor do agora.",
    "Valorize cada instante vivido.",
    "Ser grato cria um coração leve.",
    "Agradeça pelas oportunidades de aprendizado.",
    "A gratidão é a chave para a felicidade duradoura.",
    "Valorize a beleza que está ao seu redor.",
    "Ser grato transforma a percepção do mundo.",
    "Agradeça pelas pessoas que te inspiram.",
    "Gratidão mantém a alma serena.",
    "Valorize cada conquista, mesmo que pequena.",
    "Ser grato torna a vida mais doce.",
    "Agradeça por tudo que você é e tem."
],
    "cansado": [
    "Você merece descansar, não se culpe por isso.",
    "O descanso é parte da conquista.",
    "Pausar é tão importante quanto agir.",
    "Seu corpo precisa de cuidado e carinho.",
    "Você já fez muito, reconheça sua entrega.",
    "Descansar não é perder tempo, é recarregar forças.",
    "O cansaço não diminui sua capacidade.",
    "Você merece uma pausa para respirar.",
    "Cada pausa é uma forma de autocuidado.",
    "Não é preguiça, é necessidade.",
    "Sua energia é preciosa, preserve-a.",
    "Você já fez o suficiente por hoje.",
    "Seu corpo fala, ouça com amor.",
    "O descanso renova sua mente.",
    "Você não precisa se cobrar além do limite.",
    "Dormir também é produtividade.",
    "Você é humano, não uma máquina.",
    "Cuidar de si é parte da jornada.",
    "O mundo pode esperar enquanto você se recupera.",
    "Você merece sentir-se leve de novo.",
    "Seu corpo agradece por cada pausa.",
    "Você tem direito ao descanso.",
    "Um momento de calma recarrega sua energia.",
    "Você não precisa fazer tudo de uma vez.",
    "Sua saúde vem em primeiro lugar.",
    "O descanso é o combustível do sucesso.",
    "O cansaço não apaga sua força.",
    "Desacelerar também é avançar.",
    "Você merece se desligar por um instante.",
    "O amanhã trará novas energias.",
    "Hoje você já deu o seu melhor.",
    "Cuidar do corpo é cuidar da mente.",
    "O cansaço é um sinal, não uma falha.",
    "Você merece noites tranquilas.",
    "O descanso de hoje será sua força amanhã.",
    "Sua paz é mais valiosa que a pressa.",
    "Você tem permissão para parar.",
    "Cada pausa é um ato de amor-próprio.",
    "A vida também é feita de silêncios.",
    "Você já conquistou muito, descanse com orgulho.",
    "O descanso abre espaço para a criatividade.",
    "Você merece leveza.",
    "Uma pausa não atrasa sua caminhada.",
    "O cansaço não dura para sempre.",
    "Você tem o direito de se desligar.",
    "Sua força aumenta quando você descansa.",
    "Nada é mais valioso que sua saúde.",
    "Você já deu grandes passos, agora respire.",
    "O descanso é um presente para si mesmo.",
    "Você merece acolher seu corpo e sua mente.",
    "O cansaço não apaga sua essência.",
    "Pausar é um sinal de sabedoria.",
    "Sua energia não é infinita, preserve-a.",
    "Você pode parar sem culpa.",
    "O descanso também é vitória.",
    "Você merece dormir em paz.",
    "Seu corpo precisa de carinho.",
    "O cansaço é apenas uma fase.",
    "Você já fez o bastante hoje.",
    "A vida pede pausas para ser vivida.",
    "Você é mais forte depois do descanso.",
    "Nada é mais produtivo que cuidar de si.",
    "Você merece relaxar.",
    "O mundo pode esperar um pouco.",
    "O descanso é um ato de coragem.",
    "Você já plantou muito, agora colha o silêncio.",
    "Sua energia merece ser respeitada.",
    "Não há problema em pausar.",
    "O cansaço não apaga seu valor.",
    "Você já fez a sua parte.",
    "Sua força volta com o descanso.",
    "Você merece um tempo só para si.",
    "O corpo pede pausa para florescer.",
    "Você não precisa se esgotar para ser digno.",
    "O descanso é parte do processo.",
    "Você é suficiente, mesmo parado.",
    "Seu corpo é sua casa, cuide dele.",
    "Você merece cuidar da sua energia.",
    "O cansaço é temporário, mas seu brilho é eterno.",
    "Você não precisa dar conta de tudo agora.",
    "A vida não exige pressa, mas equilíbrio.",
    "Você merece acolhimento em seu cansaço.",
    "O descanso traz clareza.",
    "Seu corpo pede calma, atenda.",
    "O cansaço é apenas um pedido por pausa.",
    "Você não precisa estar disponível o tempo todo.",
    "Sua mente merece silêncio.",
    "O descanso é uma forma de cura.",
    "Você é mais importante que suas tarefas.",
    "O corpo forte nasce de um coração descansado.",
    "Você merece um momento de paz.",
    "O cansaço não diminui sua grandeza.",
    "Pausar também é avançar.",
    "Você pode soltar o peso agora.",
    "Sua energia é preciosa demais para ser desperdiçada.",
    "Você merece uma pausa sem culpas.",
    "Seu corpo agradece pelo cuidado.",
    "O descanso é tão valioso quanto a ação.",
    "Você está no caminho certo, mesmo que pare um pouco.",
    "Sua força será renovada: permita-se descansar."
],
    "confuso": ["A confusão é parte do processo de aprender algo novo.",
    "Está tudo bem não ter todas as respostas agora.",
    "A clareza vem com o tempo.",
    "Você não precisa decidir tudo hoje.",
    "O caminho se mostra passo a passo.",
    "Mesmo na confusão, você continua avançando.",
    "A dúvida é sinal de que você está aprendendo.",
    "Tudo bem não saber para onde ir ainda.",
    "O futuro não exige pressa, só paciência.",
    "Você pode se permitir não entender tudo.",
    "A confusão abre espaço para novas descobertas.",
    "Nem sempre é preciso ter certeza para seguir.",
    "Você está em construção, e isso é lindo.",
    "As respostas chegam no momento certo.",
    "Até na dúvida existe crescimento.",
    "O agora é suficiente, mesmo sem clareza total.",
    "Você não precisa ter controle sobre tudo.",
    "A vida também é feita de incertezas.",
    "Um passo por vez é suficiente.",
    "O caminho certo se revela na caminhada.",
    "Você não precisa se cobrar por estar perdido.",
    "Confusão é parte do processo de mudança.",
    "Sua mente está se reorganizando, confie.",
    "O amanhã pode trazer novas respostas.",
    "A vida não exige pressa, apenas coragem.",
    "Você já superou outros momentos de dúvida.",
    "O importante é não desistir de buscar.",
    "A clareza sempre aparece depois da tempestade.",
    "Você pode acolher suas incertezas.",
    "Nem toda confusão é negativa, às vezes é recomeço.",
    "Você está se redescobrindo.",
    "Não há problema em não ter todas as certezas.",
    "As perguntas também fazem parte da vida.",
    "A dúvida mostra que você está refletindo.",
    "O tempo é um grande aliado da clareza.",
    "Você merece calma mesmo em meio às incertezas.",
    "Sua vida não precisa de respostas imediatas.",
    "Confusão também é oportunidade de aprender.",
    "Você já caminhou até aqui, isso já é vitória.",
    "O futuro vai se desenhar com sua paciência.",
    "Você pode confiar em si mesmo mesmo na dúvida.",
    "A clareza nasce da calma.",
    "Não ter respostas não é falha, é parte da vida.",
    "Seu coração sabe mais do que sua mente cansada.",
    "A confusão é passageira, sua força é permanente.",
    "A vida se ajeita no tempo certo.",
    "Você merece paz mesmo em meio ao caos.",
    "Você não precisa escolher tudo agora.",
    "A incerteza também pode ser liberdade.",
    "Sua história não precisa ser toda definida hoje.",
    "A confusão mostra que você está evoluindo.",
    "O desconhecido também pode ser bonito.",
    "Você não precisa correr para encontrar respostas.",
    "O que parece confuso hoje pode ser claro amanhã.",
    "A dúvida é apenas um sinal de movimento interno.",
    "Você já tem dentro de si as respostas que procura.",
    "O tempo certo revela o caminho certo.",
    "Você pode confiar no processo.",
    "Nem sempre é preciso entender, apenas sentir.",
    "A clareza vem quando você desacelera.",
    "Você não precisa ter pressa em se encontrar.",
    "Confusão não é fraqueza, é transição.",
    "Você está exatamente onde deveria estar agora.",
    "Cada dúvida é um convite ao autoconhecimento.",
    "A calma abre espaço para boas respostas.",
    "Você merece leveza, mesmo sem certezas.",
    "O tempo clareia tudo o que hoje parece nebuloso.",
    "Você já encontrou respostas antes.",
    "O que você sente é humano e válido.",
    "O caminho se constrói caminhando.",
    "Você pode se permitir não ter certezas.",
    "Não entender agora não significa não entender nunca.",
    "O universo sempre aponta uma direção.",
    "Suas dúvidas não diminuem seu valor.",
    "Você é mais forte do que suas incertezas.",
    "Até na confusão existe beleza.",
    "Cada passo dado já é avanço.",
    "Você não precisa resolver tudo de uma vez.",
    "As respostas podem vir no silêncio.",
    "O aprendizado mora nas incertezas.",
    "Você pode confiar na sua intuição.",
    "O caminho certo vai se abrir quando for a hora.",
    "A confusão não é permanente.",
    "Você é capaz de encontrar clareza.",
    "O importante é não parar.",
    "Suas dúvidas são sementes de crescimento.",
    "O amanhã pode surpreender com respostas.",
    "Você é maior que qualquer confusão.",
    "Cada pergunta já mostra evolução.",
    "A confusão pode ser o início de algo lindo.",
    "Você não precisa de perfeição, precisa de paciência.",
    "As respostas certas chegam com calma.",
    "Você pode confiar mais em si mesmo.",
    "O que parece perdido pode se transformar em encontro.",
    "Você merece paz em meio às dúvidas.",
    "Cada dúvida abre caminho para novas possibilidades.",
    "O tempo é sábio em organizar tudo.",
    "Você pode aprender com cada confusão.",
    "A clareza chega sempre no momento certo.",
    "Suas dúvidas não te definem.",
    "Você está exatamente no processo que precisa viver."
],
    "confiante": [
    "Acredite na sua força interior.",
    "Você é capaz de grandes conquistas.",
    "Confiança é a chave para o sucesso.",
    "Tenha fé em suas decisões.",
    "Sua coragem define seu caminho.",
    "Confie no seu potencial.",
    "Você nasceu para vencer.",
    "Acredite em você acima de tudo.",
    "Sua confiança abre portas.",
    "Cada desafio é uma chance de provar sua força.",
    "Você é mais forte do que pensa.",
    "Confiança é acreditar no seu próprio valor.",
    "Você tem dentro de si tudo que precisa.",
    "Sua determinação gera resultados.",
    "Confie no processo da vida.",
    "Você merece grandes conquistas.",
    "A confiança transforma sonhos em realidade.",
    "Tenha segurança nas suas escolhas.",
    "Sua voz interior é poderosa.",
    "Acredite no seu talento.",
    "Confiança atrai oportunidades.",
    "Você tem coragem para enfrentar qualquer desafio.",
    "Sua força interior é maior que qualquer obstáculo.",
    "Confie na sua jornada.",
    "Você é capaz de superar limites.",
    "Sua confiança é contagiante.",
    "Acredite no seu valor.",
    "Você tem poder para transformar sua vida.",
    "Confiança é seu maior aliado.",
    "Cada passo firme aumenta sua segurança.",
    "Você nasceu para brilhar.",
    "Confie na sua intuição.",
    "Sua confiança move montanhas.",
    "Você é capaz de realizar o impossível.",
    "Tenha fé na sua capacidade de vencer.",
    "Confiança é acreditar mesmo sem ver.",
    "Você tem dentro de si coragem e talento.",
    "Sua confiança te leva mais longe.",
    "Acredite que você consegue.",
    "Confiança é o primeiro passo para a vitória.",
    "Você é dono do seu destino.",
    "Sua força supera qualquer medo.",
    "Confie em suas habilidades.",
    "Cada vitória aumenta sua autoconfiança.",
    "Você é capaz de grandes mudanças.",
    "Confiança é acreditar em você quando ninguém mais acredita.",
    "Sua coragem é sua arma mais poderosa.",
    "Acredite na sua capacidade de adaptação.",
    "Você é forte, capaz e resiliente.",
    "Confiança é a base do sucesso.",
    "Cada desafio vencido fortalece sua segurança.",
    "Você tem tudo para alcançar seus objetivos.",
    "Confie no seu julgamento.",
    "Sua força interior é ilimitada.",
    "Acredite que você merece o melhor.",
    "Você pode mais do que imagina.",
    "Confiança é acreditar que você é suficiente.",
    "Sua determinação é invencível.",
    "Tenha coragem para ser você mesmo.",
    "Confiança é transformar incerteza em ação.",
    "Você é capaz de criar sua própria sorte.",
    "Acredite na força do seu coração.",
    "Sua segurança interior ilumina o caminho.",
    "Confiança é seguir firme mesmo com medo.",
    "Você tem poder para conquistar o que deseja.",
    "Acredite no seu brilho único.",
    "Sua coragem inspira os outros.",
    "Confiança é saber que você é capaz.",
    "Cada conquista reforça sua segurança.",
    "Você nasceu para grandes feitos.",
    "Confie na sua visão.",
    "Sua autoconfiança é sua aliada diária.",
    "Você é capaz de transformar desafios em vitórias.",
    "Confiança é acreditar que tudo é possível.",
    "Sua força vem da sua convicção.",
    "Acredite na sua determinação.",
    "Você pode enfrentar qualquer adversidade.",
    "Confiança é seguir seu caminho sem hesitar.",
    "Sua coragem é o seu guia.",
    "Você é suficiente do jeito que é.",
    "Confie que tudo que você precisa está dentro de você.",
    "Sua força interior é imbatível.",
    "Acredite que você merece vencer.",
    "Você tem habilidade para superar qualquer dificuldade.",
    "Confiança é a base da sua liberdade.",
    "Sua coragem abre novas possibilidades.",
    "Acredite na sua própria verdade.",
    "Você é forte, capaz e determinado.",
    "Confiança é o primeiro passo para qualquer realização.",
    "Sua força interior guia suas escolhas.",
    "Você tem o poder de mudar sua história.",
    "Confie em sua jornada pessoal.",
    "Sua coragem transforma obstáculos em oportunidades.",
    "Você é capaz de enfrentar qualquer desafio com firmeza.",
    "Confiança é acreditar em você mesmo todos os dias.",
    "Sua determinação supera qualquer adversidade.",
    "Acredite no seu potencial sem limites.",
    "Você nasceu para conquistar.",
    "Confiança é a luz que ilumina seus passos.",
    "Sua autoconfiança te leva além do que imagina."
],
    "esperançoso": [
    "Sempre há um amanhã melhor.",
    "A esperança é o combustível da vida.",
    "Acredite em dias melhores.",
    "Mesmo na dificuldade, a luz vem.",
    "O futuro guarda boas surpresas.",
    "Cada amanhecer traz novas oportunidades.",
    "Nunca perca a fé na vida.",
    "A esperança transforma desafios em força.",
    "Acredite que tudo pode melhorar.",
    "O amanhã é cheio de possibilidades.",
    "Nunca subestime o poder de acreditar.",
    "Cada dificuldade traz uma lição valiosa.",
    "A esperança renova a alma.",
    "Acredite que o melhor ainda está por vir.",
    "Sempre há uma saída.",
    "O amanhã é uma página em branco para escrever.",
    "A esperança faz o impossível parecer possível.",
    "Cada dia é uma nova chance.",
    "Acredite no poder do tempo.",
    "A esperança é o que mantém a força.",
    "Sempre há motivos para sorrir.",
    "Cada experiência prepara algo melhor.",
    "Nunca perca a fé no amanhã.",
    "A esperança ilumina o caminho.",
    "Acredite que mudanças positivas vêm.",
    "O futuro depende da sua perseverança.",
    "Cada passo mantém a esperança viva.",
    "A vida sempre oferece novas oportunidades.",
    "Tenha fé nos dias que virão.",
    "A esperança é um farol na escuridão.",
    "Confie que algo bom está chegando.",
    "Cada amanhecer é um presente.",
    "A esperança é uma escolha diária.",
    "Nunca perca a confiança no futuro.",
    "Cada desafio traz novos horizontes.",
    "A esperança nos mantém firmes.",
    "Acredite que você pode superar.",
    "O amanhã é cheio de possibilidades.",
    "A vida sempre se renova.",
    "A esperança cria força interior.",
    "Cada obstáculo traz uma oportunidade.",
    "O futuro reserva conquistas incríveis.",
    "Tenha esperança, mesmo nos dias difíceis.",
    "Cada dia é um novo começo.",
    "A esperança é a luz que guia o coração.",
    "Nunca desista de acreditar.",
    "O melhor ainda está por vir.",
    "A esperança nos impulsiona para frente.",
    "Cada dificuldade prepara algo maior.",
    "Acredite no poder da mudança.",
    "O amanhã é sempre cheio de promessas.",
    "A esperança transforma medos em força.",
    "Cada amanhecer renova a alma.",
    "Nunca perca a fé no que virá.",
    "A esperança é semente de realizações.",
    "Acredite que você merece o melhor.",
    "Cada passo firme leva a conquistas.",
    "O futuro é moldado por quem acredita.",
    "A esperança nos dá coragem para seguir.",
    "Cada desafio é passageiro.",
    "Acredite que dias melhores chegam.",
    "O amanhã traz novas oportunidades.",
    "A esperança mantém o coração tranquilo.",
    "Cada dificuldade fortalece a fé.",
    "Nunca deixe de acreditar na vida.",
    "A esperança nos faz continuar.",
    "Cada amanhecer traz renovação.",
    "Confie que tudo se ajeitará.",
    "A esperança inspira ação.",
    "Cada desafio é um convite para crescer.",
    "O futuro pertence aos que acreditam.",
    "A esperança transforma expectativas em realidade.",
    "Acredite que algo positivo está a caminho.",
    "Cada dia é chance de recomeço.",
    "A esperança dá sentido aos momentos difíceis.",
    "Nunca perca a fé em você mesmo.",
    "Cada amanhecer é promessa de oportunidades.",
    "A esperança mantém a força viva.",
    "Confie que o melhor ainda virá.",
    "Cada passo mantém a esperança acesa.",
    "A vida sempre oferece novos caminhos.",
    "A esperança gera coragem.",
    "Cada dificuldade prepara novas conquistas.",
    "Acredite no poder do amanhã.",
    "O futuro reserva coisas incríveis.",
    "Cada amanhecer traz possibilidades.",
    "A esperança nos mantém em movimento.",
    "Tenha fé que dias bons virão.",
    "Cada desafio fortalece a confiança no futuro.",
    "A esperança é força silenciosa.",
    "Acredite que cada momento tem propósito.",
    "Cada passo firme aproxima da vitória.",
    "O amanhã é cheio de surpresas positivas.",
    "A esperança inspira gratidão.",
    "Nunca perca a fé na vida e no amor.",
    "Cada amanhecer é um novo começo.",
    "A esperança nos faz perseverar.",
    "Confie que mudanças boas acontecerão.",
    "Cada desafio traz oportunidade de crescimento.",
    "A esperança é luz mesmo nos dias escuros."
],
    "animado": [
    "Hoje é um dia cheio de possibilidades!",
    "Energia positiva atrai coisas boas.",
    "Sinta a empolgação e siga em frente.",
    "A vida é mais divertida quando você se anima.",
    "Transforme entusiasmo em ação.",
    "O mundo responde à sua energia.",
    "Faça cada momento valer a pena.",
    "Sinta o ritmo da vida e dance junto.",
    "Alegria e entusiasmo movem montanhas.",
    "A empolgação é contagiosa, compartilhe!",
    "A cada passo, mais energia positiva.",
    "Viva com paixão e animação.",
    "A motivação vem da sua empolgação.",
    "Sinta entusiasmo em cada desafio.",
    "A energia que você transmite retorna.",
    "Faça do entusiasmo sua força diária.",
    "A vida fica mais leve com animação.",
    "O entusiasmo é combustível da ação.",
    "Aproveite o dia com alegria.",
    "A empolgação abre portas para oportunidades.",
    "Cada novo começo é motivo para se animar.",
    "Celebre a vida com entusiasmo.",
    "O mundo precisa da sua energia positiva.",
    "Deixe a animação guiar suas escolhas.",
    "Sinta entusiasmo e contamine todos ao redor.",
    "Viva o momento com alegria intensa.",
    "O entusiasmo cria oportunidades incríveis.",
    "A energia de hoje é sua maior aliada.",
    "Transforme entusiasmo em conquistas.",
    "Sinta prazer no que você faz.",
    "A vida é mais leve quando se sente animado.",
    "Faça cada momento especial com energia.",
    "O entusiasmo é o primeiro passo para o sucesso.",
    "A empolgação cria experiências inesquecíveis.",
    "Viva cada dia com coração animado.",
    "Sinta entusiasmo e inspire outros.",
    "Energia positiva atrai soluções.",
    "A empolgação transforma rotina em aventura.",
    "Faça das pequenas vitórias grandes motivos de alegria.",
    "Sorria e compartilhe seu entusiasmo.",
    "Viva cada instante como se fosse único.",
    "O entusiasmo abre portas para o inesperado.",
    "A energia de agora é sua oportunidade.",
    "Sinta paixão pelo que faz.",
    "Faça o hoje incrível com animação.",
    "O entusiasmo é a chave da criatividade.",
    "Viva com intensidade e alegria.",
    "A empolgação é contagiante, espalhe!",
    "Faça da energia positiva um hábito.",
    "Transforme cada desafio em motivo de animação.",
    "Sinta alegria e energia em tudo que faz.",
    "A animação cria oportunidades mágicas.",
    "A vida é mais leve quando se sente motivado.",
    "Sorrir com entusiasmo muda o dia.",
    "Cada instante é motivo para celebrar.",
    "A empolgação é força que move ações.",
    "Sinta-se vivo e cheio de energia.",
    "Transforme entusiasmo em conquistas reais.",
    "Faça o melhor do seu dia com energia.",
    "Viva cada experiência com paixão.",
    "A animação abre caminhos para novas aventuras.",
    "O entusiasmo transforma desafios em diversão.",
    "Sinta alegria em cada passo dado.",
    "Cada dia é um presente para se animar.",
    "Faça do entusiasmo seu guia diário.",
    "O mundo responde à sua energia positiva.",
    "Sinta-se motivado e confiante.",
    "A empolgação cria momentos memoráveis.",
    "Viva com entusiasmo e coragem.",
    "Cada passo animado aproxima você do sucesso.",
    "A alegria de hoje é a força de amanhã.",
    "Faça da animação um hábito diário.",
    "A energia positiva transforma tudo ao redor.",
    "Sinta alegria intensa em cada momento.",
    "Viva o dia com empolgação e gratidão.",
    "Cada pequeno gesto pode ser motivo de animação.",
    "O entusiasmo torna tudo mais leve.",
    "Sorria e inspire quem está ao redor.",
    "Faça do entusiasmo seu combustível diário.",
    "A vida é mais divertida quando se sente animado.",
    "A empolgação cria oportunidades únicas.",
    "Sinta alegria e energia em cada ação.",
    "Viva cada instante como se fosse especial.",
    "Faça de hoje um dia incrível.",
    "O entusiasmo transforma rotina em magia.",
    "Sinta prazer em cada conquista.",
    "Compartilhe sua energia positiva.",
    "Cada desafio vencido aumenta sua animação.",
    "Viva com paixão e entusiasmo genuíno.",
    "Sinta-se animado para novas aventuras.",
    "A alegria transforma qualquer situação.",
    "Faça de cada vitória um motivo para sorrir.",
    "O entusiasmo gera oportunidades inesperadas.",
    "Sinta energia e gratidão em tudo.",
    "Viva o momento com intensidade e animação.",
    "Cada ação com entusiasmo conta.",
    "Faça do hoje uma celebração da vida.",
    "O entusiasmo ilumina o caminho.",
    "Sorria e contagie o mundo com energia positiva.",
    "A vida é melhor quando se está animado."
],
    "leve": [
    "Respire fundo e sinta a leveza.",
    "Deixe a vida fluir com tranquilidade.",
    "Sinta-se livre para ser você mesmo.",
    "Solte o que não te faz bem.",
    "Cada dia é leve quando você escolhe sorrir.",
    "Viva com leveza e simplicidade.",
    "O peso some quando você deixa ir.",
    "Aproveite cada instante sem pressa.",
    "Deixe a alegria guiar seus passos.",
    "A leveza nasce da gratidão.",
    "Sinta a paz em cada gesto.",
    "Deixe a vida te levar suavemente.",
    "Caminhe com leveza e confiança.",
    "A vida é mais leve quando se é gentil.",
    "Solte o passado e viva o presente.",
    "A leveza vem do coração tranquilo.",
    "Desfrute o momento sem ansiedade.",
    "Sinta leveza em cada respiração.",
    "A vida flui melhor quando se está leve.",
    "Deixe-se envolver pela paz interior.",
    "Sorria e sinta-se leve.",
    "A leveza é encontrada na simplicidade.",
    "Soltar é libertar-se da carga desnecessária.",
    "Viva com serenidade e leveza.",
    "A paz interior cria leveza no dia a dia.",
    "Aproveite a vida sem peso no coração.",
    "A leveza é uma escolha consciente.",
    "Caminhe com leveza e coragem.",
    "Sinta alegria sem esforço.",
    "A simplicidade traz leveza à alma.",
    "Respire e deixe as preocupações irem embora.",
    "Leveza é abraçar o presente sem medo.",
    "A vida se torna mais leve com gratidão.",
    "Sinta o vento da liberdade.",
    "Desfrute cada instante com leveza.",
    "A leveza nasce da aceitação.",
    "Soltar é encontrar a paz.",
    "Caminhe leve e confiante.",
    "O coração leve atrai felicidade.",
    "Sinta a serenidade em cada momento.",
    "Leveza é estar em harmonia consigo mesmo.",
    "Deixe o peso para trás.",
    "A vida é leve quando se aprecia cada instante.",
    "Sinta liberdade em pequenas coisas.",
    "A leveza transforma rotina em alegria.",
    "Respire e sinta-se livre.",
    "Caminhe com leveza e alegria.",
    "Soltar cria espaço para o novo.",
    "Viva com simplicidade e leveza.",
    "Cada respiração consciente traz leveza.",
    "Leveza é encontrar equilíbrio no coração.",
    "Deixe a alegria fluir naturalmente.",
    "Sinta leveza em cada ação.",
    "A paz interior torna tudo mais leve.",
    "Sorrir traz leveza instantânea.",
    "Viva com leveza, sem amarras.",
    "Deixe o amor guiar sua leveza.",
    "Soltar é um ato de coragem.",
    "A vida flui melhor com leveza.",
    "Sinta-se leve e sereno.",
    "Cada instante pode ser leve e feliz.",
    "A leveza nasce do desapego.",
    "Caminhe sem pressa e com leveza.",
    "Sorria e deixe a leveza tomar conta.",
    "Aproveite cada momento leve e simples.",
    "Soltar preocupações traz leveza.",
    "A paz interior gera leveza no corpo e mente.",
    "Viva com leveza e autenticidade.",
    "Sinta leveza e liberdade em cada passo.",
    "Deixe fluir e sinta leveza.",
    "Caminhe leve e cheio de gratidão.",
    "A simplicidade cria leveza.",
    "Sorria para sentir leveza.",
    "Cada respiração consciente aumenta a leveza.",
    "Deixe ir o que pesa.",
    "Leveza é sentir alegria sem esforço.",
    "Viva o presente com leveza.",
    "A tranquilidade traz leveza.",
    "Soltar cria espaço para felicidade.",
    "Cada gesto gentil traz leveza.",
    "Caminhe com leveza e esperança.",
    "Respire e sinta-se leve e livre.",
    "A leveza transforma desafios em aprendizado.",
    "Viva sem peso e com leveza.",
    "Sinta alegria e leveza juntos.",
    "Cada amanhecer traz leveza.",
    "A simplicidade torna tudo mais leve.",
    "Sorrir cria leveza instantânea.",
    "Caminhe com leveza e confiança.",
    "Soltar é abraçar a liberdade.",
    "Cada momento pode ser leve e especial.",
    "Viva com leveza e autenticidade.",
    "Deixe o coração leve e feliz.",
    "A paz interior traz leveza ao dia.",
    "Sinta-se leve e otimista.",
    "Caminhe com leveza e amor no coração.",
    "Cada gesto consciente gera leveza.",
    "Soltar preocupações cria espaço para felicidade.",
    "A leveza transforma o cotidiano em prazer.",
    "Viva com leveza, alegria e gratidão."
],
    "realizado": [
    "Você conquistou algo incrível hoje.",
    "Sinta orgulho de cada vitória.",
    "O esforço valeu a pena, parabéns!",
    "Cada passo te trouxe até aqui.",
    "Celebre suas conquistas diárias.",
    "Realização nasce do trabalho consistente.",
    "Você é capaz de grandes feitos.",
    "A sensação de dever cumprido é única.",
    "Cada desafio vencido te fortalece.",
    "Reconheça sua própria evolução.",
    "Orgulhe-se de quem você está se tornando.",
    "A realização é fruto de dedicação.",
    "Você merece sentir satisfação pelo que conquistou.",
    "Cada conquista é um degrau para o próximo objetivo.",
    "Valorize seus progressos, grandes ou pequenos.",
    "Você fez acontecer, e isso importa.",
    "O caminho percorrido é tão valioso quanto a meta.",
    "Celebre cada vitória interna.",
    "Sinta orgulho das decisões que te trouxeram até aqui.",
    "Cada passo firme é motivo de realização.",
    "Você está construindo uma história de sucesso.",
    "Reconheça o esforço por trás de cada conquista.",
    "A realização é uma recompensa pelo seu empenho.",
    "Cada objetivo alcançado é um marco importante.",
    "Orgulhe-se de cada pequena vitória.",
    "O esforço de hoje constrói a satisfação de amanhã.",
    "Você é capaz de transformar sonhos em realidade.",
    "Sinta orgulho de sua trajetória.",
    "Cada conquista fortalece sua confiança.",
    "A realização vem da persistência.",
    "Valorize sua dedicação diária.",
    "Cada objetivo alcançado merece comemoração.",
    "Você fez o seu melhor, e isso é suficiente.",
    "Orgulhe-se das escolhas que te fizeram crescer.",
    "Cada esforço vale a sensação de realização.",
    "A satisfação vem de dentro, reconheça-a.",
    "Você está no caminho certo para grandes conquistas.",
    "Cada vitória é um reflexo do seu empenho.",
    "Celebre a jornada, não apenas o resultado.",
    "Você merece sentir-se realizado.",
    "Cada passo dado com propósito traz realização.",
    "Orgulhe-se de tudo que superou até aqui.",
    "Cada meta cumprida é motivo de orgulho.",
    "A realização é fruto de perseverança.",
    "Reconheça o valor de suas conquistas.",
    "Você está crescendo a cada dia.",
    "Celebre suas conquistas, grandes ou pequenas.",
    "Cada esforço conta para sua realização.",
    "Você fez a diferença na sua própria história.",
    "Orgulhe-se do progresso que fez.",
    "Cada vitória fortalece sua determinação.",
    "A sensação de dever cumprido é incomparável.",
    "Você é capaz de alcançar tudo que deseja.",
    "Cada meta conquistada é um motivo de alegria.",
    "Sinta-se realizado por cada avanço.",
    "Cada esforço superado merece reconhecimento.",
    "A realização é o reflexo da sua dedicação.",
    "Você constrói resultados consistentes com esforço.",
    "Cada conquista é prova da sua competência.",
    "Orgulhe-se do caminho percorrido.",
    "Cada desafio superado traz satisfação.",
    "Você merece sentir orgulho do que conquistou.",
    "Cada meta atingida fortalece seu potencial.",
    "Celebre cada vitória como se fosse única.",
    "Cada esforço é um passo para a realização.",
    "Você está alcançando grandes resultados.",
    "Cada conquista confirma sua capacidade.",
    "Orgulhe-se do seu trabalho e dedicação.",
    "Cada objetivo alcançado é reflexo do seu esforço.",
    "Você merece sentir-se pleno.",
    "Cada vitória diária te aproxima da realização completa.",
    "Reconheça seu próprio valor e conquistas.",
    "Cada progresso é um motivo para comemorar.",
    "Você está no caminho certo para grandes feitos.",
    "Cada desafio vencido traz orgulho.",
    "Orgulhe-se do seu crescimento constante.",
    "Cada meta cumprida é motivo de satisfação.",
    "Você merece se sentir realizado todos os dias.",
    "Cada esforço faz a diferença no resultado final.",
    "Reconheça as vitórias, mesmo as pequenas.",
    "Cada conquista fortalece sua confiança.",
    "Orgulhe-se das escolhas que fizeram você chegar até aqui.",
    "Cada passo adiante é motivo de realização.",
    "Você constrói sucesso com perseverança.",
    "Cada meta atingida é prova da sua força.",
    "Celebre suas vitórias com alegria.",
    "Cada conquista é resultado do seu esforço diário.",
    "Você merece sentir orgulho da sua trajetória.",
    "Cada avanço é motivo de gratidão e orgulho.",
    "Orgulhe-se do quanto você evoluiu.",
    "Cada vitória fortalece sua determinação para os próximos desafios.",
    "Você está fazendo acontecer, continue assim.",
    "Cada meta alcançada é reflexo da sua dedicação.",
    "Celebre cada conquista com alegria genuína.",
    "Cada esforço supera desafios e traz realização.",
    "Você merece sentir satisfação por tudo que conquistou.",
    "Cada vitória confirma sua capacidade e talento.",
    "Orgulhe-se de tudo que conseguiu realizar.",
    "Cada conquista é um degrau para novos objetivos.",
    "Sinta-se realizado, você fez acontecer!"
],
    "inspirado": [
    "Acredite no poder que existe dentro de você.",
    "Todo passo que você dá é um avanço.",
    "Grandes conquistas começam com pequenos esforços.",
    "O impossível é apenas o possível esperando para acontecer.",
    "Você é mais capaz do que imagina.",
    "Transforme seus sonhos em metas e suas metas em conquistas.",
    "O sucesso começa na mente.",
    "Cada desafio é uma oportunidade disfarçada.",
    "Nunca subestime o poder da persistência.",
    "Sua determinação é seu maior superpoder.",
    "Coragem é dar o primeiro passo, mesmo com medo.",
    "Hoje é a chance de criar algo incrível.",
    "Você tem tudo que precisa para vencer.",
    "Grandes ideias começam com pequenos gestos.",
    "O melhor ainda está por vir.",
    "Acredite em si mesmo, sempre.",
    "A ação transforma sonhos em realidade.",
    "Cada dia é uma nova oportunidade.",
    "Você é capaz de superar qualquer obstáculo.",
    "O sucesso é construído com disciplina e foco.",
    "Siga em frente, mesmo que devagar.",
    "A vida recompensa quem se arrisca.",
    "O esforço de hoje será a vitória de amanhã.",
    "Acredite, insista e conquiste.",
    "O verdadeiro poder está na sua atitude.",
    "Inspire-se no que te faz feliz.",
    "Nunca é tarde para recomeçar.",
    "Confie no seu processo.",
    "Grandes vitórias exigem coragem.",
    "A motivação te impulsiona, mas a disciplina te mantém.",
    "Seu potencial é ilimitado.",
    "Transforme dificuldades em aprendizado.",
    "Cada passo dado é um passo mais próximo do sucesso.",
    "Acredite no seu talento.",
    "O impossível de hoje será o normal de amanhã.",
    "Seja a melhor versão de você mesmo.",
    "Toda jornada começa com o primeiro passo.",
    "Sua força é maior do que qualquer adversidade.",
    "Faça acontecer, não espere acontecer.",
    "Perseverança é a chave do sucesso.",
    "A coragem transforma sonhos em realidade.",
    "Hoje é o dia perfeito para tentar algo novo.",
    "O sucesso começa fora da zona de conforto.",
    "Você pode mais do que pensa.",
    "Não desista antes de tentar.",
    "A paixão move montanhas.",
    "Aprenda, evolua e vença.",
    "Acredite no seu brilho próprio.",
    "Cada pequeno esforço conta.",
    "O medo é apenas um degrau para o sucesso.",
    "Você tem dentro de si a força para vencer.",
    "Não existe limite para quem acredita.",
    "O futuro pertence aos ousados.",
    "Transforme medos em oportunidades.",
    "O progresso é construído dia após dia.",
    "Faça do seu hoje algo memorável.",
    "Você é capaz de realizar grandes feitos.",
    "Cada desafio é uma chance de crescimento.",
    "O melhor investimento é acreditar em você.",
    "Sua dedicação vale mais do que qualquer sorte.",
    "Acredite no impossível e faça acontecer.",
    "Confie na jornada, mesmo sem ver o caminho completo.",
    "Pequenos passos geram grandes mudanças.",
    "Tenha coragem de ser extraordinário.",
    "Acredite em milagres, mas trabalhe por eles.",
    "Você é maior que seus obstáculos.",
    "Faça de cada dia um novo começo.",
    "O sucesso nasce da persistência.",
    "Inspire-se e inspire outros ao seu redor.",
    "A força interior vence qualquer dificuldade.",
    "Hoje é seu momento de brilhar.",
    "Cada esforço conta para a vitória.",
    "O poder da mudança está em suas mãos.",
    "Não pare até se orgulhar.",
    "O melhor da vida está na ação.",
    "Você é capaz de reinventar seu destino.",
    "Sua atitude define seu futuro.",
    "O impossível existe apenas na mente.",
    "Nunca subestime sua própria força.",
    "Acredite no valor dos seus sonhos.",
    "Você é feito para superar.",
    "A disciplina transforma vontade em conquista.",
    "Cada obstáculo é um convite para crescer.",
    "Seu sucesso começa com um passo.",
    "A coragem abre portas que o medo fecha.",
    "O mundo precisa da sua luz.",
    "Faça do seu esforço sua maior recompensa.",
    "Tudo é possível quando você acredita.",
    "Siga firme, mesmo diante das dificuldades.",
    "O poder da mente move montanhas.",
    "Tenha fé no seu próprio caminho.",
    "Grandes conquistas começam com coragem.",
    "Acredite no que você pode fazer hoje.",
    "Você tem dentro de si todo o potencial.",
    "Transforme sonhos em realidade com ação.",
    "O sucesso é fruto de quem não desiste.",
    "Faça de cada dia uma vitória.",
    "A inspiração nasce da ação.",
    "Você pode mudar o mundo com sua dedicação.",
    "Seja a força que transforma desafios em conquistas."
],
    "estressado": [
    "Respire fundo: você é maior que o estresse.",
    "Uma pausa agora pode trazer clareza depois.",
    "O descanso faz parte da vitória.",
    "Você não precisa carregar tudo sozinho.",
    "Tudo bem se desligar por um instante.",
    "Pequenas pausas renovam grandes forças.",
    "O estresse não define sua capacidade.",
    "Você merece leveza.",
    "Uma mente calma enxerga soluções melhores.",
    "Desacelerar é um ato de coragem.",
    "Você já superou dias mais pesados.",
    "Sua saúde vem antes de qualquer obrigação.",
    "O equilíbrio é mais importante que a pressa.",
    "Respire, solte, permita-se.",
    "Você pode priorizar o que importa.",
    "O mundo não vai parar se você descansar.",
    "Você tem direito a dizer “não”.",
    "Seu corpo pede cuidado: ouça-o.",
    "Estresse não é sinal de fraqueza, é sinal de excesso.",
    "Você não precisa ser perfeito.",
    "Tudo pode ser feito um passo de cada vez.",
    "Ser produtivo não é estar sobrecarregado.",
    "Sua paz vale mais que a correria.",
    "O descanso de hoje é a energia de amanhã.",
    "Você pode delegar, não precisa carregar tudo.",
    "O autocuidado é parte do sucesso.",
    "Pausar também é produzir.",
    "Você não precisa provar nada a ninguém.",
    "A calma traz clareza.",
    "Você está fazendo o melhor possível.",
    "Não existe problema em pedir ajuda.",
    "Você merece equilíbrio.",
    "O estresse é passageiro, sua força é duradoura.",
    "Você tem capacidade de reorganizar seu tempo.",
    "Uma pausa curta pode mudar seu dia.",
    "Você é mais importante que suas tarefas.",
    "A vida é mais do que cobranças.",
    "Seu corpo agradece quando você descansa.",
    "A calma é uma escolha diária.",
    "Você tem o direito de cuidar de si.",
    "O estresse não controla quem você é.",
    "Você já fez muito hoje, reconheça isso.",
    "Seu bem-estar vale cada minuto de descanso.",
    "Você não precisa se cobrar tanto.",
    "Uma pausa agora não é perda, é ganho.",
    "Sua mente precisa de espaço para florescer.",
    "Você pode respirar fundo e soltar o peso.",
    "A leveza é mais produtiva que a pressa.",
    "Você é humano, não máquina.",
    "O descanso também é parte da jornada.",
    "Uma pausa ajuda a enxergar novas soluções.",
    "Você tem o poder de desacelerar.",
    "Seu esforço já é suficiente.",
    "O silêncio pode ser um grande aliado.",
    "Você não precisa abraçar o mundo hoje.",
    "O equilíbrio vem antes do resultado.",
    "Cuidar de si é prioridade.",
    "Você merece momentos de paz.",
    "Não se cobre além do necessário.",
    "A calma gera mais resultados que a pressa.",
    "Você pode soltar o que não depende de você.",
    "O estresse não é o fim, é um sinal de pausa.",
    "Você merece viver com leveza.",
    "Pequenos respiros mudam grandes dias.",
    "Você não está sozinho nessa luta.",
    "Cada pausa é um ato de autocuidado.",
    "Você pode simplificar sua rotina.",
    "Nem tudo precisa ser feito agora.",
    "O importante é o progresso, não a perfeição.",
    "Você pode cuidar de si sem culpa.",
    "Estresse não dura para sempre.",
    "Seu valor não depende da sua produtividade.",
    "Pausar não é fraqueza, é inteligência.",
    "Você já é suficiente.",
    "O descanso recarrega sua criatividade.",
    "Você pode deixar para amanhã o que não cabe hoje.",
    "O equilíbrio traz mais energia.",
    "Sua saúde é prioridade número um.",
    "Não precisa se cobrar além do possível.",
    "Você pode desligar e recomeçar.",
    "O autocuidado é uma forma de força.",
    "O que importa é sua paz interior.",
    "Você já avançou muito, reconheça.",
    "O corpo pede calma, atenda.",
    "Você pode desacelerar sem culpa.",
    "Sua paz vale mais que a pressa.",
    "O mundo não exige perfeição de você.",
    "Você merece tranquilidade.",
    "Estresse não é seu estado natural.",
    "Sua vida é mais do que tarefas.",
    "O descanso de hoje é sua força de amanhã.",
    "Você pode respirar e começar de novo.",
    "Não precisa correr o tempo todo.",
    "A vida também é feita de pausas.",
    "O silêncio ajuda a organizar o caos.",
    "Você é mais importante do que os prazos.",
    "O estresse é passageiro, sua força é permanente.",
    "Você não está sozinho nesse processo.",
    "Você merece leveza todos os dias.",
    "A paz é sua maior conquista."
],
    "sozinho": [
    "Você nunca está realmente sozinho, sempre há alguém que se importa.",
    "Sua presença já é valiosa neste mundo.",
    "Às vezes, a solidão é apenas um pedido da alma por descanso.",
    "Há pessoas que torcem por você, mesmo em silêncio.",
    "O universo sempre prepara encontros inesperados.",
    "Você é importante demais para ser esquecido.",
    "Sua vida tem impacto na de muitas pessoas.",
    "O isolamento não diminui seu valor.",
    "Há laços invisíveis conectando você a outros corações.",
    "Sua luz inspira mais do que imagina.",
    "Você merece amor e companhia.",
    "O mundo é melhor porque você existe.",
    "Sempre existe alguém disposto a ouvir você.",
    "Sua solidão não define quem você é.",
    "Há pessoas que sentem sua falta.",
    "A distância não apaga conexões verdadeiras.",
    "Você já é suficiente, mesmo sem ninguém por perto.",
    "Sua presença no mundo nunca passa despercebida.",
    "Há mais carinho guardado para você do que imagina.",
    "Você não precisa enfrentar tudo sozinho.",
    "Mesmo em silêncio, há quem pense em você.",
    "Seu coração é digno de afeto.",
    "Você merece sentir-se acolhido.",
    "O amor pode chegar de formas inesperadas.",
    "Sua vida importa para muita gente.",
    "O carinho que você dá volta multiplicado.",
    "Sua história está entrelaçada à de muitos.",
    "Mesmo em solidão, você carrega memórias de amor.",
    "Você é visto, mesmo quando se sente invisível.",
    "O mundo seria diferente sem você.",
    "Sua voz tem valor e merece ser ouvida.",
    "Você tem espaço especial no coração de alguém.",
    "Cada pessoa que você já tocou carrega sua marca.",
    "Você é parte essencial de muitas histórias.",
    "Sua essência nunca estará sozinha.",
    "O carinho verdadeiro sempre encontra um caminho.",
    "Sua vida é mais conectada do que imagina.",
    "Há sempre alguém que gostaria de estar ao seu lado agora.",
    "Você merece afeto, hoje e sempre.",
    "O amor pode estar mais perto do que parece.",
    "Sua existência traz sentido a outras vidas.",
    "Você não precisa se esconder em sua solidão.",
    "O mundo precisa do que só você pode oferecer.",
    "O amor próprio também é companhia.",
    "Mesmo em silêncio, seu coração se conecta ao universo.",
    "Você é amado de formas que talvez não perceba.",
    "Sua companhia é preciosa.",
    "Alguém pensa em você neste momento.",
    "Você é lembrado com carinho por muitas pessoas.",
    "Sua essência nunca será esquecida.",
    "Há abraços esperando por você.",
    "Sua vida inspira mais do que você sabe.",
    "Alguém agradece por ter você na vida.",
    "O mundo é mais bonito porque você faz parte dele.",
    "Sua presença é um presente.",
    "A solidão é um estado, não uma sentença.",
    "Você é merecedor de afeto constante.",
    "Sua jornada importa para além de você.",
    "Há conexões verdadeiras que sempre estarão com você.",
    "Você já deixou marcas de amor em muitas pessoas.",
    "Sua energia atrai o que é bom.",
    "Você é parte de algo muito maior.",
    "Sua alma merece companhia e carinho.",
    "O amor encontra caminhos invisíveis.",
    "Você não está esquecido.",
    "Sua luz alcança lugares que você nem imagina.",
    "Você já é amado pelo simples fato de existir.",
    "O mundo precisa da sua presença.",
    "Você é acolhido, mesmo quando não percebe.",
    "Há pessoas que se alegram só de pensar em você.",
    "Sua companhia tem valor único.",
    "O carinho pode vir das formas mais simples.",
    "Sua solidão não diminui sua importância.",
    "Você é parte essencial do todo.",
    "Seu coração nunca está verdadeiramente só.",
    "Você é digno de conexões sinceras.",
    "Há sempre espaço para novos laços.",
    "Sua vida tem muito significado.",
    "Alguém agradece secretamente por você existir.",
    "Sua energia já transformou outras pessoas.",
    "Você é lembrado com gratidão.",
    "A vida coloca pessoas especiais em nosso caminho.",
    "Você não precisa se sentir invisível.",
    "Sua voz importa.",
    "Você tem valor, mesmo em silêncio.",
    "Há sempre um coração aberto para você.",
    "Sua solidão não é permanente.",
    "Você já faz parte de muitas memórias felizes.",
    "O amor está no ar que você respira.",
    "Sua existência tem propósito.",
    "Você pode se permitir ser acolhido.",
    "Há sempre alguém pronto para caminhar ao seu lado.",
    "Sua vida já inspirou outras pessoas.",
    "Você é digno de atenção e carinho.",
    "Mesmo distante, há quem te queira bem.",
    "Sua companhia é única e insubstituível.",
    "O mundo precisa do seu brilho.",
    "Você é amado exatamente como é.",
    "Sua presença nunca passa despercebida.",
    "Você não está só: sempre há laços invisíveis de amor."
]
}

# Emojis + labels
opcoes = [
    {"emoji": "😊", "label": "Feliz", "key": "feliz"},
    {"emoji": "😞", "label": "Triste", "key": "triste"},
    {"emoji": "😰", "label": "Ansioso", "key": "ansioso"},
    {"emoji": "💪", "label": "Motivado", "key": "motivado"},
    {"emoji": "😌", "label": "Calmo", "key": "calmo"},
    {"emoji": "🙏", "label": "Grato", "key": "grato"},
    {"emoji": "😴", "label": "Cansado", "key": "cansado"},
    {"emoji": "🤔", "label": "Confuso", "key": "confuso"},
    {"emoji": "😎", "label": "Confiante", "key": "confiante"},
    {"emoji": "🌅", "label": "Esperançoso", "key": "esperançoso"},
    {"emoji": "🤩", "label": "Animado", "key": "animado"},
    {"emoji": "🍃", "label": "Leve", "key": "leve"},
    {"emoji": "🏆", "label": "Realizado", "key": "realizado"},
    {"emoji": "✨", "label": "Inspirado", "key": "inspirado"},
    {"emoji": "😣", "label": "Estressado", "key": "estressado"},
    {"emoji": "🌙", "label": "Sozinho", "key": "sozinho"}
]

# Função para navegar
def go_to_feedback(sentimento):
    st.session_state.sentimento = sentimento
    st.session_state.feedback = random.choice(feedbacks.get(sentimento, ["Não há feedback disponível."]))
    st.session_state.page = "feedback"
    st.rerun()

# Função para converter imagem em base64
def load_image_base64(file_path):
    with open(file_path, "rb") as f:
        return base64.b64encode(f.read()).decode()

# CSS ajustado
st.markdown("""
    <style>
    .main-title {
        text-align: center;
        font-size: 28px;
        color: #FF8C00;  /* cor laranja */
        font-weight: bold;
        margin-bottom: 1em;
    }
    .title-container {
        display: flex;
        justify-content: center;
        align-items: center;
        flex-wrap: wrap;
        gap: 0.5em;
        font-size: 22px;
        text-align: center;
    }
    .title-heart {
        animation: heartbeat 1s infinite;
        color: #FFD700;
    }
    .title-text {
        color: #FF8C00;   /* agora mesma cor do main-title */
        font-weight: bold;
    }
    @keyframes heartbeat {
        0%, 100% { transform: scale(1); }
        25%, 75% { transform: scale(1.2); }
        50% { transform: scale(1); }
    }
    </style>
""", unsafe_allow_html=True)

# Página Inicial
if st.session_state.page == "home":
    st.markdown("""
        <div class="main-title">Setembro Amarelo - Falar é a melhor solução</div>
        <div class="title-container">
            <span class="title-heart">💛</span>
            <span class="title-text">A TGA quer saber: Como você está se sentindo hoje?</span>
        </div>
    """, unsafe_allow_html=True)

    # Botões
    for i in range(0, len(opcoes), 4):
        cols = st.columns(4)
        for j, opcao in enumerate(opcoes[i:i+4]):
            col = cols[j]
            if col.button(f"{opcao['emoji']} {opcao['label']}", key=opcao["key"]):
                go_to_feedback(opcao["key"])

    # Frase + logo centralizada
    encoded = load_image_base64("tga.png")
    st.markdown(
        f"""
        <div class="footer-container">
            <div class="footer-text">Cada resposta é única e exclusiva para você</div>
            <div class="footer-logo">
                <img src="data:image/png;base64,{encoded}">
            </div>
        </div>
        """,
        unsafe_allow_html=True
    )

# Página de Feedback
elif st.session_state.page == "feedback":
    emoji = next(o['emoji'] for o in opcoes if o['key'] == st.session_state.sentimento)
    st.markdown(
        f"<h2 style='text-align: center; font-size: 28px; color: #2563eb;'>Você escolheu: {st.session_state.sentimento.capitalize()} {emoji}</h2>",
        unsafe_allow_html=True
    )
    st.markdown("<hr>", unsafe_allow_html=True)
    st.markdown(
        f"<div style='font-size:22px; font-weight:600; color:#2563eb; text-align:center; margin-top:25px;'>{st.session_state.feedback}</div>",
        unsafe_allow_html=True
    )
